swagger: "2.0"
info:
  title: Hematopy Web API
  version: v1
  description: Python and Blood
  contact:
    name: Argo Crew / ArgoPy
    email: contact+hematopy@argocrew.io
    url: https://github.com/ArgoCrew/hematopy
host: hematopy-dev-gustavorps.herokuapp.com
basePath: /api/v1/
schemes:
  - https
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
tags:
  - name: Donation
paths:
  /donations:
    post:
      tags:
      - Donation
      summary: Add a new donation and generate image banner
      description: ''
      operationId: createDonation
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/DonateAction"
      responses:
        405:
          description: Invalid input
definitions:
  DonateAction:
    type: object
    required:
      - recipient_image
      - recipient_name
      - recipient_blood_type
      - location_name
      - location_address_street
      - location_address_number
      - location_address_district
      - location_address_locality
      - location_address_region
      - location_address_postal_code      
    properties:
      recipient_image:
        type: string
        format: binary
      recipient_name:
        type: string
      recipient_blood_type:
        type: string
        enum:
        - A-
        - A+
        - B-
        - B+
        - AB-
        - AB+
        - O-
        - O+
      location_name:
        type: string
      location_address_street:
        type: string
      location_address_number:
        type: string
      location_address_district:
        type: string
      location_address_locality:
        type: string
      location_address_region:
        type: string
      location_address_postal_code:
        type: number